language: python
python: 3.6
cache: pip


before_install:
- pip install -U pre-commit
- pip install django==1.11

script:
- pre-commit run --all-files
- python ./manage.py test
- python manage.py makemessages --locale=uk --locale=en --domain=django
- git diff --numstat | awk '{if ($1>1 || $2>1) { exit 1 } else { exit 0 }}'
